apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aspnetapp

resources:
  - namespace.yaml
  - mssql-secret.yaml
  - mssql-pvc.yaml
  - mssql-statefulset.yaml
  - web-deployment.yaml
  - ingress.yaml

# 'labels' replaces deprecated 'commonLabels'
labels:
  - includeSelectors: true
    pairs:
      project: prueba-dummy-flbetances
      managed-by: kustomize
