# SonarQube project configuration
sonar.projectKey=prueba-dummy-flbetances
sonar.projectName=Prueba-Dummy-FLBetances
sonar.projectVersion=1.0

# Source paths
sonar.sources=src/app/aspnetapp
sonar.exclusions=**/wwwroot/lib/**,**/bin/**,**/obj/**,**/*.min.js,**/*.min.css

# Encoding
sonar.sourceEncoding=UTF-8

# Quality Gate
sonar.qualitygate.wait=true
